# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_ACTIVITY_MISSION = descriptor.Descriptor(
  name='ACTIVITY_MISSION',
  full_name='Table.ACTIVITY_MISSION',
  filename='c_table_activity.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Table.ACTIVITY_MISSION.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='Table.ACTIVITY_MISSION.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='Table.ACTIVITY_MISSION.description', index=2,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='icon', full_name='Table.ACTIVITY_MISSION.icon', index=3,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ACTIVITY_MISSION_ARRAY = descriptor.Descriptor(
  name='ACTIVITY_MISSION_ARRAY',
  full_name='Table.ACTIVITY_MISSION_ARRAY',
  filename='c_table_activity.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='rows', full_name='Table.ACTIVITY_MISSION_ARRAY.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ACTIVITY_AWARD = descriptor.Descriptor(
  name='ACTIVITY_AWARD',
  full_name='Table.ACTIVITY_AWARD',
  filename='c_table_activity.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='score', full_name='Table.ACTIVITY_AWARD.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='award_list', full_name='Table.ACTIVITY_AWARD.award_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ACTIVITY_AWARD_ARRAY = descriptor.Descriptor(
  name='ACTIVITY_AWARD_ARRAY',
  full_name='Table.ACTIVITY_AWARD_ARRAY',
  filename='c_table_activity.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='rows', full_name='Table.ACTIVITY_AWARD_ARRAY.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import common_activity_pb2
import common_game_res_pb2

_ACTIVITY_MISSION.fields_by_name['type'].enum_type = common_activity_pb2._ACTIVITYTYPE
_ACTIVITY_MISSION_ARRAY.fields_by_name['rows'].message_type = _ACTIVITY_MISSION
_ACTIVITY_AWARD.fields_by_name['award_list'].message_type = common_game_res_pb2._GAMERES
_ACTIVITY_AWARD_ARRAY.fields_by_name['rows'].message_type = _ACTIVITY_AWARD

class ACTIVITY_MISSION(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIVITY_MISSION

class ACTIVITY_MISSION_ARRAY(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIVITY_MISSION_ARRAY

class ACTIVITY_AWARD(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIVITY_AWARD

class ACTIVITY_AWARD_ARRAY(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIVITY_AWARD_ARRAY

