# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_SERVER_NOTICE_MSG = descriptor.Descriptor(
  name='SERVER_NOTICE_MSG',
  full_name='Table.SERVER_NOTICE_MSG',
  filename='c_table_servernoticemsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Table.SERVER_NOTICE_MSG.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='Table.SERVER_NOTICE_MSG.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SERVER_NOTICE_MSG_ARRAY = descriptor.Descriptor(
  name='SERVER_NOTICE_MSG_ARRAY',
  full_name='Table.SERVER_NOTICE_MSG_ARRAY',
  filename='c_table_servernoticemsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='rows', full_name='Table.SERVER_NOTICE_MSG_ARRAY.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SERVER_NOTICE_MSG_ARRAY.fields_by_name['rows'].message_type = _SERVER_NOTICE_MSG

class SERVER_NOTICE_MSG(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVER_NOTICE_MSG

class SERVER_NOTICE_MSG_ARRAY(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVER_NOTICE_MSG_ARRAY

