# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_GAMERESSOURCE = descriptor.EnumDescriptor(
  name='GameResSource',
  full_name='Common.GameResSource',
  filename='GameResSource',
  values=[
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_UNSPICIFIED', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_MISSION', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_INSTANCE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PORTAL', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_GM_COMMAND', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_UPGRADE_EQUIP', index=5, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ADVANCED_EQUIP', index=6, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_INLAY_GEM', index=7, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_UPGRADE_GEM', index=8, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ADVANCED_SKILL', index=9, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_UNLOCK_HERO', index=10, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ARENA', index=11, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ARENA_CLEAR_CD', index=12, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_WORLD_BOSS', index=13, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_COLLECTION', index=14, number=29,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_COLLECTION_SHOP', index=15, number=30,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_TERRITORY', index=16, number=31,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_USE_ITEM', index=17, number=32,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ACTIVITY_AWARD', index=18, number=33,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_MOMO_AWARD', index=19, number=34,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_UPGRADE_SKILL', index=20, number=35,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_UPDATE_SKILL_POINT', index=21, number=36,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_SP', index=22, number=37,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_DAILY_MISSION_AWARD', index=23, number=38,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_SELL_ITEM', index=24, number=39,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_DAILY_AWARD', index=25, number=40,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ONLINE_AWARD', index=26, number=41,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_MOCK_EXAM_AWARD', index=27, number=42,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_EXAM_RANK_AWARD', index=28, number=43,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_RECHARGE_AWARD', index=29, number=44,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_SANDBAGSWAR_AWARD', index=30, number=45,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ROB_AWARD', index=31, number=46,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_REFRESH_CHALL_HISTORY', index=32, number=47,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_NATURE_INC_SP', index=33, number=48,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_EXCHANGE_ITEM', index=34, number=49,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PRINTING_PRESS', index=35, number=50,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_CLEAR_TRANSFORM_CD', index=36, number=51,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_CLIMB_TOWER_AWARD', index=37, number=52,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_HERO_CELL', index=38, number=53,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_CLIMB_TOWER_COUNT', index=39, number=54,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_MSG_AWARD', index=40, number=55,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_REVIVE_IN_INSTANCE', index=41, number=56,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ADVANCED_HERO', index=42, number=57,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_LOTTERY', index=43, number=58,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_LOTTERY_SHOP', index=44, number=59,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_REVIVE_PVP_HERO', index=45, number=60,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_RESET_EXTRA_SP', index=46, number=61,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_DEGREE_DEVOUR', index=47, number=62,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_TERR_ROB', index=48, number=63,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_LEV_AWARD', index=49, number=64,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_DEGREE_ALL_DEVOUR', index=50, number=65,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_SIGN_AWARD', index=51, number=66,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_GYM_LEASE', index=52, number=67,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_GROUP_BUILD', index=53, number=68,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_CREATE_GROUP', index=54, number=69,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_FIRE_GROUP_CAPTAIN', index=55, number=70,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_GROUP_OUTPUT', index=56, number=71,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_STREET_WAR', index=57, number=72,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_GVG_AWARD', index=58, number=73,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_GROUP_SCORE_AWARD', index=59, number=74,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_SKILL_POINT', index=60, number=75,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_D_NORMAL_GIFTBAG', index=61, number=76,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_D_VIP_GIFTBAG', index=62, number=77,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_STREET_WAR_CHALLENGE', index=63, number=78,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_STAR_AWARD', index=64, number=79,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_LOTTERY_DRAGON', index=65, number=80,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_COLLECT_CLOTHES', index=66, number=81,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PUT_ON_CLOTHES', index=67, number=82,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_LOTTERY_SCHOOL', index=68, number=83,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_SUPPLEMENT_SIGN', index=69, number=84,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ACTIVE_HERO_COMNINATION', index=70, number=85,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_UNLOCK_FELLOW_CELL', index=71, number=86,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ARENA_SHOP', index=72, number=87,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_FIRST_RECHARGE_AWARD', index=73, number=88,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_STREET_SHOP', index=74, number=89,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_DEGREE_SHOP', index=75, number=90,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_GOLD_INVEST', index=76, number=91,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_AWARD_GOLD_INVEST', index=77, number=92,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_OPERATION', index=78, number=93,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_TRANSFER_HERO_EXP', index=79, number=94,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_WEEK_LOGIN_AWARD', index=80, number=95,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_WEEK_RECHARGE_AWARD', index=81, number=96,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_WEEK_RUSH_PURCHASE', index=82, number=97,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_FC_RACE', index=83, number=98,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_TEAM_PVE', index=84, number=99,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PASS_RACE', index=85, number=100,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_RECHARGE', index=86, number=101,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_DEGREE_DECOMPOSITION', index=87, number=120,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_RECRUIT_PAOJIE', index=88, number=121,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_COLLECT_HERO', index=89, number=122,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ADVANCED_CHUNLI', index=90, number=123,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_COLLECT_GEM', index=91, number=124,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_COLLECT_DEGREE', index=92, number=125,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PURPLE_AWARD', index=93, number=126,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_FC_RANK_AWARD', index=94, number=127,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_LEV_RANK_AWARD', index=95, number=128,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ARENA_RANK_AWARD', index=96, number=129,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_REFINE_MAGIC', index=97, number=130,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_FINISH_REFINE_MAGIC', index=98, number=131,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_AWARD_REFINE_MAGIC', index=99, number=132,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ARTIFACT_EXCHANGE', index=100, number=135,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PUT_ON_ARTIFACT', index=101, number=136,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_UPGRADE_ARTIFACT', index=102, number=137,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ADVANCE_ARTIFACT', index=103, number=138,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_INLAY_ARTIFACT', index=104, number=139,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_UPGRADE_GEM_ARTIFACT', index=105, number=140,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_GEM_EXCHANGE', index=106, number=141,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_EQUIP_STARUP', index=107, number=142,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ACTIVE_TITLE', index=108, number=143,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_INNER_ACVITITY', index=109, number=144,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_TOURNAMENT', index=110, number=145,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_TOURNAMENT_SHOP', index=111, number=146,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ARTIFACT_DECOMPOSE', index=112, number=147,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_LEV_SHOP_GOODS', index=113, number=148,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_ITEM', index=114, number=149,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_GROWUP', index=115, number=150,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_TURNTABLE', index=116, number=151,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_RESET_TURNTABLE', index=117, number=152,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PET_FEED', index=118, number=153,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_VIP_DAILY_AWARD', index=119, number=154,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_SEASON_AWARD', index=120, number=155,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_COST_GOLD', index=121, number=156,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_DAILY_SCORE_AWARD', index=122, number=157,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PET_HATCH', index=123, number=158,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PET_LEVUP', index=124, number=159,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PET_ADVANCE', index=125, number=160,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PET_MISSION', index=126, number=161,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_FULL_AWARD', index=127, number=162,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_MEAT_BUN', index=128, number=163,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ITEM_COMPOSITE', index=129, number=164,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_VIP_WEEK_AWARD', index=130, number=165,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_LIMITED_CHALLENGE', index=131, number=166,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_RESET_HERO_EXP', index=132, number=167,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_LIMITED_MISSION', index=133, number=168,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ADVANCED_DEGREE', index=134, number=169,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_EGG_LOTTERY_RANK_AWARD', index=135, number=170,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_ITEM_EXPIRE', index=136, number=171,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_RUNNING_RACE_COUNT', index=137, number=172,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_SINGLE_RUNNING_RACE', index=138, number=173,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_RANK_RUNNING_RACE', index=139, number=174,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PRACTICE_EXCHANGE', index=140, number=175,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_PRACTICE', index=141, number=176,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_REVERT_PRACTICE', index=142, number=177,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_REVERT_HERO_START', index=143, number=178,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_SOURCE_BUY_GROUP_SP_WELFARE', index=144, number=179,
      options=None,
      type=None),
  ],
  options=None,
)


_GAMERESTYPE = descriptor.EnumDescriptor(
  name='GameResType',
  full_name='Common.GameResType',
  filename='GameResType',
  values=[
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_INVALID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_COIN', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_GOLD', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_EXP', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_ITEM', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_FAME', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_SP', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_VIP_EXP', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_SKILL_POINT', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_SCORE', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_HERO', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_PET', index=11, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_RES_TYPE_MAX', index=12, number=12,
      options=None,
      type=None),
  ],
  options=None,
)


GAME_RES_SOURCE_UNSPICIFIED = 0
GAME_RES_SOURCE_MISSION = 1
GAME_RES_SOURCE_INSTANCE = 2
GAME_RES_SOURCE_PORTAL = 3
GAME_RES_SOURCE_GM_COMMAND = 5
GAME_RES_SOURCE_UPGRADE_EQUIP = 7
GAME_RES_SOURCE_ADVANCED_EQUIP = 8
GAME_RES_SOURCE_INLAY_GEM = 9
GAME_RES_SOURCE_UPGRADE_GEM = 10
GAME_RES_SOURCE_ADVANCED_SKILL = 11
GAME_RES_SOURCE_UNLOCK_HERO = 12
GAME_RES_SOURCE_ARENA = 15
GAME_RES_SOURCE_ARENA_CLEAR_CD = 16
GAME_RES_SOURCE_WORLD_BOSS = 20
GAME_RES_SOURCE_COLLECTION = 29
GAME_RES_SOURCE_COLLECTION_SHOP = 30
GAME_RES_SOURCE_TERRITORY = 31
GAME_RES_SOURCE_USE_ITEM = 32
GAME_RES_SOURCE_ACTIVITY_AWARD = 33
GAME_RES_SOURCE_MOMO_AWARD = 34
GAME_RES_SOURCE_UPGRADE_SKILL = 35
GAME_RES_SOURCE_UPDATE_SKILL_POINT = 36
GAME_RES_SOURCE_BUY_SP = 37
GAME_RES_SOURCE_DAILY_MISSION_AWARD = 38
GAME_RES_SOURCE_SELL_ITEM = 39
GAME_RES_SOURCE_DAILY_AWARD = 40
GAME_RES_SOURCE_ONLINE_AWARD = 41
GAME_RES_SOURCE_MOCK_EXAM_AWARD = 42
GAME_RES_SOURCE_EXAM_RANK_AWARD = 43
GAME_RES_SOURCE_RECHARGE_AWARD = 44
GAME_RES_SOURCE_SANDBAGSWAR_AWARD = 45
GAME_RES_SOURCE_ROB_AWARD = 46
GAME_RES_SOURCE_REFRESH_CHALL_HISTORY = 47
GAME_RES_SOURCE_NATURE_INC_SP = 48
GAME_RES_SOURCE_EXCHANGE_ITEM = 49
GAME_RES_SOURCE_PRINTING_PRESS = 50
GAME_RES_SOURCE_CLEAR_TRANSFORM_CD = 51
GAME_RES_SOURCE_CLIMB_TOWER_AWARD = 52
GAME_RES_SOURCE_HERO_CELL = 53
GAME_RES_SOURCE_BUY_CLIMB_TOWER_COUNT = 54
GAME_RES_SOURCE_MSG_AWARD = 55
GAME_RES_SOURCE_REVIVE_IN_INSTANCE = 56
GAME_RES_SOURCE_ADVANCED_HERO = 57
GAME_RES_SOURCE_LOTTERY = 58
GAME_RES_SOURCE_LOTTERY_SHOP = 59
GAME_RES_SOURCE_REVIVE_PVP_HERO = 60
GAME_RES_SOURCE_RESET_EXTRA_SP = 61
GAME_RES_SOURCE_DEGREE_DEVOUR = 62
GAME_RES_SOURCE_TERR_ROB = 63
GAME_RES_SOURCE_LEV_AWARD = 64
GAME_RES_SOURCE_DEGREE_ALL_DEVOUR = 65
GAME_RES_SOURCE_SIGN_AWARD = 66
GAME_RES_SOURCE_GYM_LEASE = 67
GAME_RES_SOURCE_GROUP_BUILD = 68
GAME_RES_SOURCE_CREATE_GROUP = 69
GAME_RES_SOURCE_FIRE_GROUP_CAPTAIN = 70
GAME_RES_SOURCE_GROUP_OUTPUT = 71
GAME_RES_SOURCE_STREET_WAR = 72
GAME_RES_SOURCE_GVG_AWARD = 73
GAME_RES_SOURCE_GROUP_SCORE_AWARD = 74
GAME_RES_SOURCE_BUY_SKILL_POINT = 75
GAME_RES_SOURCE_BUY_D_NORMAL_GIFTBAG = 76
GAME_RES_SOURCE_BUY_D_VIP_GIFTBAG = 77
GAME_RES_SOURCE_BUY_STREET_WAR_CHALLENGE = 78
GAME_RES_SOURCE_STAR_AWARD = 79
GAME_RES_SOURCE_LOTTERY_DRAGON = 80
GAME_RES_SOURCE_COLLECT_CLOTHES = 81
GAME_RES_SOURCE_PUT_ON_CLOTHES = 82
GAME_RES_SOURCE_LOTTERY_SCHOOL = 83
GAME_RES_SOURCE_SUPPLEMENT_SIGN = 84
GAME_RES_SOURCE_ACTIVE_HERO_COMNINATION = 85
GAME_RES_SOURCE_UNLOCK_FELLOW_CELL = 86
GAME_RES_SOURCE_ARENA_SHOP = 87
GAME_RES_SOURCE_FIRST_RECHARGE_AWARD = 88
GAME_RES_SOURCE_STREET_SHOP = 89
GAME_RES_SOURCE_DEGREE_SHOP = 90
GAME_RES_SOURCE_BUY_GOLD_INVEST = 91
GAME_RES_SOURCE_AWARD_GOLD_INVEST = 92
GAME_RES_SOURCE_OPERATION = 93
GAME_RES_SOURCE_TRANSFER_HERO_EXP = 94
GAME_RES_SOURCE_WEEK_LOGIN_AWARD = 95
GAME_RES_SOURCE_WEEK_RECHARGE_AWARD = 96
GAME_RES_SOURCE_WEEK_RUSH_PURCHASE = 97
GAME_RES_SOURCE_FC_RACE = 98
GAME_RES_SOURCE_TEAM_PVE = 99
GAME_RES_SOURCE_PASS_RACE = 100
GAME_RES_SOURCE_RECHARGE = 101
GAME_RES_SOURCE_DEGREE_DECOMPOSITION = 120
GAME_RES_SOURCE_RECRUIT_PAOJIE = 121
GAME_RES_SOURCE_COLLECT_HERO = 122
GAME_RES_SOURCE_ADVANCED_CHUNLI = 123
GAME_RES_SOURCE_COLLECT_GEM = 124
GAME_RES_SOURCE_COLLECT_DEGREE = 125
GAME_RES_SOURCE_PURPLE_AWARD = 126
GAME_RES_SOURCE_FC_RANK_AWARD = 127
GAME_RES_SOURCE_LEV_RANK_AWARD = 128
GAME_RES_SOURCE_ARENA_RANK_AWARD = 129
GAME_RES_SOURCE_REFINE_MAGIC = 130
GAME_RES_SOURCE_FINISH_REFINE_MAGIC = 131
GAME_RES_SOURCE_AWARD_REFINE_MAGIC = 132
GAME_RES_SOURCE_ARTIFACT_EXCHANGE = 135
GAME_RES_SOURCE_PUT_ON_ARTIFACT = 136
GAME_RES_SOURCE_UPGRADE_ARTIFACT = 137
GAME_RES_SOURCE_ADVANCE_ARTIFACT = 138
GAME_RES_SOURCE_INLAY_ARTIFACT = 139
GAME_RES_SOURCE_UPGRADE_GEM_ARTIFACT = 140
GAME_RES_SOURCE_GEM_EXCHANGE = 141
GAME_RES_SOURCE_EQUIP_STARUP = 142
GAME_RES_SOURCE_ACTIVE_TITLE = 143
GAME_RES_SOURCE_INNER_ACVITITY = 144
GAME_RES_SOURCE_TOURNAMENT = 145
GAME_RES_SOURCE_TOURNAMENT_SHOP = 146
GAME_RES_SOURCE_ARTIFACT_DECOMPOSE = 147
GAME_RES_SOURCE_BUY_LEV_SHOP_GOODS = 148
GAME_RES_SOURCE_BUY_ITEM = 149
GAME_RES_SOURCE_GROWUP = 150
GAME_RES_SOURCE_TURNTABLE = 151
GAME_RES_SOURCE_RESET_TURNTABLE = 152
GAME_RES_SOURCE_PET_FEED = 153
GAME_RES_SOURCE_VIP_DAILY_AWARD = 154
GAME_RES_SOURCE_SEASON_AWARD = 155
GAME_RES_SOURCE_COST_GOLD = 156
GAME_RES_SOURCE_DAILY_SCORE_AWARD = 157
GAME_RES_SOURCE_PET_HATCH = 158
GAME_RES_SOURCE_PET_LEVUP = 159
GAME_RES_SOURCE_PET_ADVANCE = 160
GAME_RES_SOURCE_PET_MISSION = 161
GAME_RES_SOURCE_FULL_AWARD = 162
GAME_RES_SOURCE_MEAT_BUN = 163
GAME_RES_SOURCE_ITEM_COMPOSITE = 164
GAME_RES_SOURCE_VIP_WEEK_AWARD = 165
GAME_RES_SOURCE_LIMITED_CHALLENGE = 166
GAME_RES_SOURCE_RESET_HERO_EXP = 167
GAME_RES_SOURCE_LIMITED_MISSION = 168
GAME_RES_SOURCE_ADVANCED_DEGREE = 169
GAME_RES_SOURCE_EGG_LOTTERY_RANK_AWARD = 170
GAME_RES_SOURCE_ITEM_EXPIRE = 171
GAME_RES_SOURCE_BUY_RUNNING_RACE_COUNT = 172
GAME_RES_SOURCE_SINGLE_RUNNING_RACE = 173
GAME_RES_SOURCE_RANK_RUNNING_RACE = 174
GAME_RES_SOURCE_PRACTICE_EXCHANGE = 175
GAME_RES_SOURCE_PRACTICE = 176
GAME_RES_SOURCE_REVERT_PRACTICE = 177
GAME_RES_SOURCE_REVERT_HERO_START = 178
GAME_RES_SOURCE_BUY_GROUP_SP_WELFARE = 179
GAME_RES_TYPE_INVALID = 0
GAME_RES_TYPE_COIN = 1
GAME_RES_TYPE_GOLD = 2
GAME_RES_TYPE_EXP = 3
GAME_RES_TYPE_ITEM = 4
GAME_RES_TYPE_FAME = 5
GAME_RES_TYPE_SP = 6
GAME_RES_TYPE_VIP_EXP = 7
GAME_RES_TYPE_SKILL_POINT = 8
GAME_RES_TYPE_SCORE = 9
GAME_RES_TYPE_HERO = 10
GAME_RES_TYPE_PET = 11
GAME_RES_TYPE_MAX = 12



_GAMERES = descriptor.Descriptor(
  name='GameRes',
  full_name='Common.GameRes',
  filename='common_game_res.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Common.GameRes.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='param_list', full_name='Common.GameRes.param_list', index=1,
      number=2, type=18, cpp_type=2, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='expire_time', full_name='Common.GameRes.expire_time', index=2,
      number=10, type=16, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='Common.GameRes.data', index=3,
      number=101, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GAMERESWITHPROB = descriptor.Descriptor(
  name='GameResWithProb',
  full_name='Common.GameResWithProb',
  filename='common_game_res.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='prob', full_name='Common.GameResWithProb.prob', index=0,
      number=1, type=17, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='Common.GameResWithProb.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='param_list', full_name='Common.GameResWithProb.param_list', index=2,
      number=3, type=18, cpp_type=2, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GAMERES.fields_by_name['type'].enum_type = _GAMERESTYPE
_GAMERESWITHPROB.fields_by_name['type'].enum_type = _GAMERESTYPE

class GameRes(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMERES

class GameResWithProb(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMERESWITHPROB

