# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_ACTIVITYTYPE = descriptor.EnumDescriptor(
  name='ActivityType',
  full_name='Common.ActivityType',
  filename='ActivityType',
  values=[
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_INVALID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_ELITE_CHALLENGE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_DEVIL_CHALLENGE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_ARENA_CHALLENGE', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_TERRITORY_BONUS', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_UPGRADE_EQUIP', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_COMPLETE_DM', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_BUY_SP', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_MOMO_FRIENDS', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_SANDBAGS_WARS', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_MOCK_EXAM', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_PRINTING_PRESS', index=11, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_CLIMB_TOWER', index=12, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_STREET_WAR', index=13, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_TEAM_PVE', index=14, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_TOURNAMENT', index=15, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_TURNTABLE', index=16, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_LOTTERY', index=17, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTIVITY_TYPE_END', index=18, number=18,
      options=None,
      type=None),
  ],
  options=None,
)


ACTIVITY_TYPE_INVALID = 0
ACTIVITY_TYPE_ELITE_CHALLENGE = 1
ACTIVITY_TYPE_DEVIL_CHALLENGE = 2
ACTIVITY_TYPE_ARENA_CHALLENGE = 3
ACTIVITY_TYPE_TERRITORY_BONUS = 4
ACTIVITY_TYPE_UPGRADE_EQUIP = 5
ACTIVITY_TYPE_COMPLETE_DM = 6
ACTIVITY_TYPE_BUY_SP = 7
ACTIVITY_TYPE_MOMO_FRIENDS = 8
ACTIVITY_TYPE_SANDBAGS_WARS = 9
ACTIVITY_TYPE_MOCK_EXAM = 10
ACTIVITY_TYPE_PRINTING_PRESS = 11
ACTIVITY_TYPE_CLIMB_TOWER = 12
ACTIVITY_TYPE_STREET_WAR = 13
ACTIVITY_TYPE_TEAM_PVE = 14
ACTIVITY_TYPE_TOURNAMENT = 15
ACTIVITY_TYPE_TURNTABLE = 16
ACTIVITY_TYPE_LOTTERY = 17
ACTIVITY_TYPE_END = 18


_ACTIVITYMISSION_STATE = descriptor.EnumDescriptor(
  name='State',
  full_name='Common.ActivityMission.State',
  filename='State',
  values=[
    descriptor.EnumValueDescriptor(
      name='STATE_UNFINISHED', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATE_FINISHED', index=1, number=1,
      options=None,
      type=None),
  ],
  options=None,
)


_ACTIVITYMISSION = descriptor.Descriptor(
  name='ActivityMission',
  full_name='Common.ActivityMission',
  filename='common_activity.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Common.ActivityMission.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='Common.ActivityMission.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='finish_cond', full_name='Common.ActivityMission.finish_cond', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='progress', full_name='Common.ActivityMission.progress', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='score_addition', full_name='Common.ActivityMission.score_addition', index=4,
      number=5, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _ACTIVITYMISSION_STATE,
  ],
  options=None)


_ACTIVITYAWARDSTATUS = descriptor.Descriptor(
  name='ActivityAwardStatus',
  full_name='Common.ActivityAwardStatus',
  filename='common_activity.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='score', full_name='Common.ActivityAwardStatus.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='awarded', full_name='Common.ActivityAwardStatus.awarded', index=1,
      number=2, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ACTIVITY = descriptor.Descriptor(
  name='Activity',
  full_name='Common.Activity',
  filename='common_activity.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='activity_list', full_name='Common.Activity.activity_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='award_list', full_name='Common.Activity.award_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ACTIVITYMISSION.fields_by_name['type'].enum_type = _ACTIVITYTYPE
_ACTIVITYMISSION.fields_by_name['state'].enum_type = _ACTIVITYMISSION_STATE
_ACTIVITY.fields_by_name['activity_list'].message_type = _ACTIVITYMISSION
_ACTIVITY.fields_by_name['award_list'].message_type = _ACTIVITYAWARDSTATUS

class ActivityMission(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIVITYMISSION

class ActivityAwardStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIVITYAWARDSTATUS

class Activity(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIVITY

