# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_SCENETYPE = descriptor.EnumDescriptor(
  name='SceneType',
  full_name='Common.SceneType',
  filename='SceneType',
  values=[
    descriptor.EnumValueDescriptor(
      name='SCENE_TYPE_INVALID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SCENE_TYPE_MAIN', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SCENE_TYPE_COPY', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


SCENE_TYPE_INVALID = 0
SCENE_TYPE_MAIN = 1
SCENE_TYPE_COPY = 2




